"""line_bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZKDLhp1QpRd4cdAyoMEsfWvHsUZ0iQW
"""
from flask import Flask,request,abort
from linebot import LineBotApi,WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage,TextSendMessage
import pya3rt

app = Flask(__name__)

linebot_api = LineBotApi("uJW6OTEeZh/HD5qxSET0z9AL/qMAbQCsLCakMDIYZMIvD3ZhE5Ef93JSjJEMQZ5d6qPh35cBYCUllZKp5Eem+lR+D8XXdVDfc2GtAGVNhKpgLmvmnz/WBscuTDr7KyXaJnHuSHYnZMvh59inEg8PYgdB04t89/1O/w1cDnyilFU=")
handler = WebhookHandler("810b031b7a85d302581e98f689f327f4")

@app.route("/callback",methods=["POST"])
def callback():
  signature = request.headers["X-Line-Signature"]
  body = request.get_data(as_text=True)

  try:
    handler.handle(body,signature)
  except InvalidSignatureError:
    abort(400)
  
  return "OK"

@handler.add(MessageEvent,message=TextMessage)
def handle_message(event):
  ai_message = talk_ai(event.message.text)
  linebot_api.reply_message(event.reply_token,TextSendMessage(text=ai_message))

def talk_ai(word):
  apikey = "DZZun7AGQ9C7VYpDqsQWffXWg4xaMGQd"
  client = pya3rt.TalkClient(apikey)
  reply_message = client.talk(word)
  return reply_message["results"][0]["reply"]

if __name__ == "__main__":
  app.run()
